### ISSUE TITLE
Build fails on mono (Travis)?

### ISSUE THREAD

**Issue by urbanhusky** [adamralph/stylecop-msbuild#4]
Hi,

I'm sorry if this doesn't really fit here but it's the first place I could think about when tracking down this issue.
I have a Xamarin application, which consists mostly of portable class libraries and I'm using Travis for CI. However, the build fails on projects where StyleCop.MSBuild has been added:

```
Target StyleCop:

: error : Error initializing task StyleCopTask: The classes in the module cannot be loaded.

                Build FAILED.
```

The build log can be viewed at https://travis-ci.org/BudgetFirst/BudgetFirst/builds/136990265

**Comment by adamralph** [comment]
Hi @urbanhusky, thanks for raising this.

Unfortunately, for some reason, StyleCop fails on Linux/Mono. What I usually do is to prevent StyleCop from running in a non-Windows OS, like so:

``` XML
  <PropertyGroup Condition=" '$(OS)' != 'Windows_NT'">
    <StyleCopEnabled>false</StyleCopEnabled>
  </PropertyGroup>
```

You could probably get more sophisticated and detect the case where you are running on Windows but using Mono (I think StyleCop fails in that scenario too).

If you want to pursue the reason why StyleCop fails on Linux/Mono then I suggest you raise an issue over at the [StyleCop project](https://stylecop.codeplex.com/). StyleCop.MSBuild is just a repackaging of StyleCop for installation in projects, so changes to StyleCop itself are out of scope here.

**Comment by adamralph** [comment]
Having said that, there is also [this idea](https://github.com/adamralph/stylecop-msbuild/issues/5) I had a while back, which would reduce friction whilst StyleCop doesn't work on Linux/Mono.

**Comment by urbanhusky** [comment]
I wonder if this is possibly just a Linux+Mono issue, because I have people working on Mac that can build it and get the proper output.

**Comment by adamralph** [comment]
Interesting. IIRC I tried it using Mono on Windows and that wouldn't work so it's surprising that it works using Mono on Mac.

I think it could be quite difficult to implement #5 in the StyleCop.MSBuild package since it would need testing on all combinations of runtime and OS both initially, and each time a new version of StyleCop is released.

Until StyleCop start guaranteeing support for the combinations of runtime and OS that you are using, I think it's best if you craft a `PropertyGroup` in your csproj files which correctly sets `StyleCopEnabled` in all the combinations you want to support.

**Comment by adamralph** [comment]
Closing this discussion. @urbanhusky please comment and/or reopen if you still want to discuss anything here.
